name: "Test devenv"
on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Build the devenv shell and run any pre-commit hooks
        run: nix develop --no-pure-eval -c bash -c "just-generate && just all"
